services:
  - type: web
    name: azhen-blog-backend
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
